---
swagger: "2.0"
info:
  title: "Weather Provider API"
  version: "1.0.1"
  x-ibm-name: "weather-provider-api"
host: "myweatherprovider.mybluemix.net"
schemes:
- "https"
basePath: "/weather"
produces:
- "application/json"
paths:
  /today:
    get:
      summary: "Today's Weather"
      parameters:
      - name: "zipcode"
        in: "query"
        description: "A valid 5-digit US zip code"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/Today"
definitions:
  Today:
    type: "object"
    properties:
      zip:
        type: "string"
      hi:
        type: "integer"
      lo:
        type: "integer"
      nightHumidity:
        type: "integer"
      city:
        type: "string"
      state:
        type: "string"
      dayHumidity:
        type: "integer"
  Current:
    type: "object"
    properties:
      zip:
        type: "string"
      temperature:
        type: "integer"
      humidity:
        type: "integer"
      city:
        type: "string"
      state:
        type: "string"
x-ibm-configuration:
  enforced: true
  testable: true
  phase: "realized"
  cors:
    enabled: true
  assembly:
    execute:
    - operation-switch:
        title: "operation-switch"
        case:
        - operations:
          - verb: "get"
            path: "/today"
          execute:
          - invoke:
              title: "invoke-today"
              timeout: 60
              verb: "GET"
              cache-response: "protocol"
              cache-ttl: 900
              version: "1.0.0"
              target-url: "https://myweatherprovider.mybluemix.net/today?zipcode=$(request.parameters.zipcode)"
        otherwise: []
        version: "1.0.0"
    catch:
    - errors:
      - "ConnectionError"
      - "RuntimeError"
      execute:
      - set-variable:
          title: "Rewrite Error"
          actions:
          - set: "message.body"
            value: "{\"message\": \"Error occurred during search operation.\"}"
          version: "1.0.0"
  gateway: "datapower-gateway"
consumes:
- "application/json"
securityDefinitions:
  Google-oauth-third-party:
    type: "oauth2"
    description: ""
    flow: "implicit"
    scopes: {}
    authorizationUrl: ""
    x-tokenIntrospect:
      url: "https://api.eu-de.apiconnect.ibmcloud.com/fdutorg-dev/sb/utility/third-party-oauth/introspect/google-microservice"
  ClientId:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
security:
- ClientId: []
  Google-oauth-third-party: []
